### ISSUE TITLE
cannot import name 'Hosts'

### ISSUE THREAD

**Issue by deadstar2011** [jonhadfield/python-hosts#23] opened 2019-09-23 06:56 UTC
Hi, at 0.4.6 version had error with command:
from python_hosts import Hosts, HostsEntry

Error:"cannot import name Hosts"

At version 0.4.5 anythink work perfect

**Comment by jonhadfield** [comment] 2019-09-23 08:16
Hi, sorry, due to a change/regression I need to explore further, for this release, you'll need:
```from python_hosts.hosts import Hosts, HostsEntry```
Sorry, I'll put out a 0.4.7 release later today.

**Comment by deadstar2011** [comment] 2019-09-23 09:36
> Hi, sorry, due to a change/regression I need to explore further, for this release, you'll need:
> `from python_hosts.hosts import Hosts, HostsEntry`
> Sorry, I'll put out a 0.4.7 release later today.

**Comment by deadstar2011** [comment] 2019-09-23 09:36
thanks, friend

**Comment by jonhadfield** [comment] 2019-09-23 21:16
Fixed in 0.4.7

**Closed by jonhadfield** 2019-09-23 21:16 UTC
